# Generated by Django 3.2.12 on 2022-03-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('emp_code', models.CharField(max_length=15)),
                ('dept', models.CharField(max_length=50)),
                ('date_birth', models.DateField()),
                ('mobile_no', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('adhar_no', models.CharField(max_length=20, unique=True)),
                ('pan_no', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
